### ISSUE TITLE
Error: Argument 2 must be a function

### ISSUE THREAD

**Issue by jpacora** [y-a-v-a/node-gd#12]
I'm using Mac OS X Yosemite, trying to test the example:

// Require library 
var gd = require('node-gd');
 
// Create blank new image in memory 
var img = gd.create(200, 80);
 
// Set background color 
img.colorAllocate(0, 255, 0);
 
// Set text color 
var txtColor = img.colorAllocate(255, 0, 255);
 
// Set full path to font file 
var fontPath = '/full/path/to/font.ttf';
 
// Render string in image 
img.stringFT(txtColor, fontPath, 24, 0, 10, 60, 'Hello world!');
 
// Write image buffer to disk 
img.savePng('output.png', 1, function(err) {
  if(err) {
    throw err;
  }
});

And I getting this error:

/Users/jpacora/Documents/node/kdash/index.js:5
var img = gd.createTrueColor(200, 80);
             ^
Error: Argument 2 must be a function
    at Error (native)
    at Object.<anonymous> (/Users/jpacora/Documents/node/kdash/index.js:5:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by y-a-v-a** [comment]
Hi, @jpacora, thanks for reaching out! Since version 1.0.0, the API has changed quite much for the two functions `gd.create` and `gd.createTrueColor`. Since I decided to upgrade to Nan v2 ( https://github.com/nodejs/nan/ ), these two functions are asynchronous by default. See also the main documentation page here on GitHub. Your example should work this way:

```javascript
// Require library 
var gd = require('node-gd');

// Create blank new image in memory 
gd.create(200, 80, function(error, img) {
    // Set background color 
    img.colorAllocate(0, 255, 0);

    // Set text color 
    var txtColor = img.colorAllocate(255, 0, 255);

    // Set full path to font file 
    var fontPath = '/full/path/to/font.ttf';

    // Render string in image 
    img.stringFT(txtColor, fontPath, 24, 0, 10, 60, 'Hello world!');

    // Write image buffer to disk 
    img.savePng('output.png', 1, function(err) {
        if(err) {
            throw err;
        }
    });
});
```

If you have a reason to use the synchronous versions, you should call them as `gd.createSync` and `gd.createTrueColorSync`. I decided to do this because I wanted a) to be more truely asynchronous where possible, and b) to reflect naming conventions in NodeJS (like `fs.read` and `fs.readSync`).
Good luck. If you still have questions, drop me another message.
