### ISSUE TITLE
Node.js 4.x.x compatibility

### ISSUE THREAD

**Issue by gabrieledarrigo** [y-a-v-a/node-gd#13]
Hello,
is this package compatible with Node.js 4.x.x?
I seen that on travis.ci You build only on "0.12" and "0.10".
I ask because I have a package that use node-gd as a dependency and I like it to work on last Node.js version.

**Comment by y-a-v-a** [comment]
Hi, thanks for reaching out.
Yes, it is compatible with Node.js 4.x.x since it uses Nan2: https://github.com/nodejs/nan
It's more a matter of travis-configuration which I need to update.

Which package is it, that is dependent on node-gd? If that package is not using node-gd@1.x.x, then it will *not* support node 4.x.x. In other words, Node.js 4.x.x is supported from node-gd version 1.x.x.
Cheers,
Vincent

**Comment by y-a-v-a** [comment]
Are you referring to your package https://github.com/gabrieledarrigo/monsterid ?
Just update the package.json to let it use node-gd@1.0.1 and change "gd.createTrueColor" to "gd. createTrueColorSync", or use the async version in your file https://github.com/gabrieledarrigo/monsterid/blob/master/src/index.js

**Comment by gabrieledarrigo** [comment]
Ehi, You are the man!
How did You find monsterid?
Updated and It works like a charm, thank You very much!

**Comment by y-a-v-a** [comment]
Hi!
I found your package monsterid on the npmjs.com page. They keep track of all dependencies 😀:
https://www.npmjs.com/package/node-gd
Thanks that I could help out. If you have any further questions, don't hesitate to ask!
Cheers 🍻
