### ISSUE TITLE
Cannot find module ......./build/default/node_gd.node'

### ISSUE THREAD

**Issue by nealrs** [y-a-v-a/node-gd#15]
Hola, 

just updated to stable node v4.2.1 (on El Capitan) and getting an error when installing the package: 
![screen shot 2015-10-23 at 10 11 45 pm](https://cloud.githubusercontent.com/assets/1568188/10708362/6eb120d6-79d3-11e5-8885-9afc07710f06.png)

and then when i try to run the example (shown on tonic): 

![screen shot 2015-10-23 at 10 09 02 pm](https://cloud.githubusercontent.com/assets/1568188/10708365/7b61dc1c-79d3-11e5-838d-5e5cb3df096f.png)

i blew away my local `node_modules` dir and reinstalled, but i keep getting the same thing. I think this is a cascading problem - any suggestions? thanks!!

```
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/neal/Sites/escobar/node_modules/node-gd/js/../build/default/node_gd.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/neal/Sites/escobar/node_modules/node-gd/js/node-gd.js:139:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

```

**Comment by y-a-v-a** [comment]
Hi,
Thanks for reaching out.
Node-gd won't work on tonicdev.com since node-gd depends on a c++ addon that needs to be built based on environment specific dependencies.

Node-gd is dependent on the library libgd2, which is written in C. The c++ code in node-gd (see directory ./cpp/) uses header files from the library to compile itself to an addon which can be used by node.js.
The location of these header files differs per environment. On Linux, they usualy reside in `/usr/local/lib`. On a Mac this depends on how libgd2 is installed. When you install libgd2 with brew, the dependencies also reside in `/usr/local/lib`. When libgd2 is installed through Macports, it will reside in `/opt/local/lib`.

Using a Mac, you will also need to install Xcode and its command line tools, because both Macports and Brew will need to use them to be able to compile the cpp code into a module.

Can you attach a more detailed screenshot of the results of `npm install`? Then I can say wether the built was successful or not.

Cheers 🍻
Vincent

**Comment by y-a-v-a** [comment]
Hi,
Just to get a clearer grasp on the issue: what's the output of `find . -type f -name node_gd.node` from your project root? I.e. to verify wether node-gd actually successfully has been built.
Cheers
Vincent

**Comment by eknowles** [comment]
It is being installed, but in `/build/Release/` (I have the same issue, I'm not on El Capitan)

![](http://i.imgur.com/8QPpWNt.png)

**Comment by y-a-v-a** [comment]
Hmm that's a bit strange since on line
https://github.com/y-a-v-a/node-gd/blob/stable/js/node-gd.js#L132
and beyond both optional paths are checked wether node_gd.node resides there...
@eknowles could you post a little more context? (build or runtime error output from the console)?
Would be great.
Thanks
Vincent

**Comment by y-a-v-a** [comment]
No info received. Closing.

**Comment by quinndiggity** [comment]
I was hit by this as well, was due to libgd2 package being replaced in the ubuntu repos by libgd3 (http://packages.ubuntu.com/source/trusty/libgd2 - oldlibs)

installing libgd3 along with libgd2-xpm-dev resolved the issue for me, submitting a pull request for the README

**Comment by quinndiggity** [comment]
https://github.com/quinndiggity/node-gd/pull/1
