### ISSUE TITLE
Add gdImageStringFTEx function

### ISSUE THREAD

**Issue by aleksandr-m** [y-a-v-a/node-gd#19]
https://boutell.com/gd/manual2.0.33.html#gdImageStringFTEx

**Comment by y-a-v-a** [comment]
I noticed `node-gd` lacks some more gdImageStringFT functions, so I'll give this priority, but it still might take a while before it's implemented.

**Comment by y-a-v-a** [comment]
It's on its way, probably another week and the method should be available!

**Comment by y-a-v-a** [comment]
Just outof curiosity: for what purpose you want to plan to use `gd.Image#stringFTEx()`? As for example the `charmap` option that libgd offers is, imho, quite a bit of a useless feature since unicode/utf8 is considered the standard mostly, right now.

I've created the following API if you'd want to configure _all_ extras:
```javascript
var extras = {
    linespacing: 1.5,
    hdpi: 300,
    vdpi: 300,
    charmap: 'unicode',
    disable_kerning: false,
    xshow: true,
    return_fontpathname: true,
    use_fontconfig: false,
    fontpath: ''
};
```
The idea is that `gd.Image#stringFTEx()` will return that same object, possibly modified. E.g. in this example since `xshow` is true and `return_fontpathname` is true, the `extras` object will be updated. The property `xshow` will contain a string with kerning details and `fontpath` will contain a path to the used font file.
You need not set all of them. If for example you only want to set the line spacing, you can pass it this:
```javascript
var extras = {
    linespacing: 1.3
};
```

**Comment by aleksandr-m** [comment]
> Just outof curiosity: for what purpose you want to plan to use `gd.Image#stringFTEx()`?

Font hinting.

Tried current HEAD with different hdpi / vdpi and there is slight change in pixels.

Thanks! Looking forward for the release.

**Comment by y-a-v-a** [comment]
@aleksandr-m yay! v1.4.0 should have a complete working gd.Image#stringFTEx
Please keep reporting any findings, I'll try to fix them as soon as possible. Success!
