### ISSUE TITLE
stringFTBBox() return elements

### ISSUE THREAD

**Issue by ivanatora** [y-a-v-a/node-gd#35]
Hi again,

This is more like a discussion than an issue. stringFTBBox() currently according to the docs returns 8 (!) elements: [xll, yll, xlr, ylr, xur, yur, xul, yul]. Is there really a need for all 8 elements? Can the bounding box be anything else than a rectangle? If it is always rectangle, we need only 4 elements - x, y, width and height. I think it would make the API a bit more clear.

Regards,
Ivan

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out again.
This is due to the fact that gdImageStringFT supports an angle. So if the text is turned like 40 degrees, you would like to have the exact coordinates for the bounding box. I think your suggestion would need more calculations on the JS side, while now it is done by libgd.
Cheers,
Vincent

**Comment by ivanatora** [comment]
Ah, I see now. If the text box can be rotated then it won't go with only 4 elements. Closing this one.
