### ISSUE TITLE
Failed Installation on MacOS

### ISSUE THREAD

**Issue by haegul** [y-a-v-a/node-gd#52]
Hello. I installed node-gd recently on MacOS Sierra(10.12.6). But Installation was failed.
This is NPM installation logs. (NPM Version 5.4.0)
```
// npm install node-gd
/bin/sh: ./util.sh: Permission denied
gyp: Call to './util.sh png16' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Momo/WebstormProjects/node-gd-sample/node_modules/node-gd
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```
So I tried to sudo command together.

```
// sudo npm install node-gd
> node-gd@1.5.0 install /Users/Momo/WebstormProjects/node-gd-sample/node_modules/node-gd
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/Momo/WebstormProjects/node-gd-sample/node_modules/node-gd/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Momo/WebstormProjects/node-gd-sample/node_modules/node-gd
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```
I solved installation problem using yarn, ```yarn add node-gd```. It is fine. But, yet I don`t install using NPM. I guess ```node-gyp rebuild``` command include permission issue.

Thanks.

**Comment by y-a-v-a** [comment]
Hi, thanks for reaching out. First of all, you should not necessarily need to install anything nodejs-related as root. See for details: https://docs.npmjs.com/getting-started/fixing-npm-permissions
Apart from that, the issue you encountered could be thrown by the call to `pkg-config` in the util.sh script that node-gd utilizes. And it could be that exactly that call _should_ actually be called by root on your system, but that's just a wild guess. And since it appears to work with yarn, it's probably not even that, but maybe something with nodejs and permissions in general on your system.
Cheers 🍻 Vincent

**Comment by haegul** [comment]
I already try it. But still having problem.
Anyway, I solved this issue using yarn. Thank you for answer.
