### ISSUE TITLE
Cropping image loses transparency

### ISSUE THREAD

**Issue by Dan-baker** [y-a-v-a/node-gd#60]
When attempting to crop an image using:
`var out_img = in_img.crop(0,0,in_img.width,in_img.height/2);`
The resulting out_img will have lost the transparency from in_img. Playing around with saveAlpha options on both the in_img and out_img seems to have no effect.

**Comment by y-a-v-a** [comment]
Hi @Dan-baker, thanks for reaching out. 
That's quite an interesting finding, I must say. It clearly has to do with libgd itself, instead of with node-gd. Node-gd only passes a src and dest image to libgd, which handles the cropping. As for true color images, there possibly seems to be a bug there. A workaround which I found out is this:

```javascript
'use strict';

var fs = require('fs');
var gd = require('../js/node-gd.js');

var inImg = gd.openPng('./fixtures/input-transparent.png');
var outImg = gd.createTrueColorSync(50,50);
outImg.alphaBlending(0);
outImg.saveAlpha(1);
var color = gd.trueColorAlpha(255, 255, 255, 127);

outImg.filledRectangle(0, 0, 50, 50, color);
inImg.copy(outImg, 0, 0, 0, 0, 50, 50);


outImg.savePng(`./output/cropped.png`, (error) => {
  if (error) {
    throw error;
  }
});
```
Ignore my mix of ES5 and ES6, I was just trying to find a solution ;-). What I'm actually doing here is pre-creating the destination image, in this case 50x50 px, and draw a transparent square on it, in order to make it fully transparent, and then copy part of the source image on top of it. I hope this might be of help. Next to this, I will try and see how the cropping works on paletted images. If I have some results, I'll post it here.
Cheers,
Vincent

**Comment by Dan-baker** [comment]
Good morning, @y-a-v-a. Firstly, thanks so much for such a quick response and assistance. I have independently come to the same conclusion regarding the use of `copy` as a workaround to the issue. The fact that one can use negative numbers in the dx and dy means that it can also be used for cropping off the top & left sides of the image if required. 
I have a working solution for my requirements now but if you need any assistance in testing, then I'd be very keen to assist.

**Comment by y-a-v-a** [comment]
Hi @Dan-baker thanks for your reply. As you can see I posted an issue at libgd's github repo and they acknowledged your remark as a bug, which has been fixed. I have no clue when they will release the fix, their release cycles aren't quite frequent... Until then, best is to stick to your own alternative. And thanks for helping OSS! I will add a remark to the documentation, by the way.
Regards, Vincent
